hosts:
- name: 'all_in_one'
  roles:
    - 'CONTROLLER_LB'
    - 'COMPUTER'
disks:
  daisy: 50
  controller: 50
  compute: 50
daisy_passwd: 'r00tme'
daisy_ip: '10.20.11.2'
daisy_gateway: '10.20.11.1'
ceph_disk_name: ''
