##############################################################################
# Copyright (c) 2016 ZTE Coreporation and others.
# hu.zhijiang@zte.com.cn
# sun.jing22@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

network-config-metadata:
  title: 'zte-virtual1 network config'
  version: '0.1'
  created: 'Mon Oct 31 2016'
  comment:
networks:
  - cidr: '192.168.122.0/24'
    gateway: '192.168.122.1'
    ip_ranges:
    - 'start': '192.168.122.1'
      'end': '192.168.122.254'
    name: 'MANAGEMENT'
  - cidr: '192.168.122.0/24'
    gateway: '192.168.122.1'
    ip_ranges:
    - start: '192.168.122.1'
      end: '192.168.122.254'
    name: 'STORAGE'
  - cidr: '192.168.2.0/24'
    gateway: '192.168.2.1'
    ip_ranges:
    - 'start': '192.168.2.1'
      'end': '192.168.2.254'
    'name': 'EXTERNAL'
  - cidr: '192.168.122.0/24'
    gateway: '192.168.122.1'
    ip_ranges:
    - 'start': '192.168.122.1'
      'end': '192.168.122.254'
    name: 'PUBLICAPI'
  - cidr: '192.168.122.0/24'
    gateway: '192.168.122.1'
    ip_ranges:
    - 'start': '192.168.122.1'
      'end': '192.168.122.254'
    name: 'physnet1'

internal_vip: '192.168.122.144'

public_vip: '192.168.122.144'
