##############################################################################
# Copyright (c) 2017 ZTE Coreporation and others.
# hu.zhijiang@zte.com.cn
# sun.jing22@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
##############################################################################
# deployment configuration meta-data
deployment-scenario-metadata:
   title: ODL-L3 HA deployment
   version: 0.0.1
   created: Jun 8 2017
   comment:

##############################################################################
# Stack extentions are opnfv added value features
stack-extensions:
  - module: opendaylight

##############################################################################
# By editing the override-config sections below, you can override arbitrary
# configuration name-space settings
deploy-override-config:
  hosts:
  - name: 'controller01'
    roles:
      - 'CONTROLLER_LB'
    template: 'templates/virtual_environment/vms/controller.xml'
  - name: 'controller02'
    roles:
      - 'CONTROLLER_LB'
    template: 'templates/virtual_environment/vms/controller.xml'
  - name: 'controller03'
    roles:
      - 'CONTROLLER_LB'
    template: 'templates/virtual_environment/vms/controller.xml'
  - name: 'computer01'
    roles:
      - 'COMPUTER'
    template: 'templates/virtual_environment/vms/computer.xml'
  - name: 'computer02'
    roles:
      - 'COMPUTER'
    template: 'templates/virtual_environment/vms/computer.xml'