adapter: ipmi
hosts:
- name: 'controller01'
  roles:
    - 'CONTROLLER_LB'
  template: 'templates/virtual_environment/vms/controller.xml'
- name: 'controller02'
  roles:
    - 'CONTROLLER_LB'
  template: 'templates/virtual_environment/vms/controller.xml'
- name: 'controller03'
  roles:
    - 'CONTROLLER_LB'
  template: 'templates/virtual_environment/vms/controller.xml'
- name: 'computer01'
  roles:
    - 'COMPUTER'
  template: 'templates/virtual_environment/vms/computer.xml'
- name: 'computer02'
  roles:
    - 'COMPUTER'
  template: 'templates/virtual_environment/vms/computer.xml'
disks:
  daisy: 50
daisy_passwd: 'r00tme'
daisy_ip: '10.20.7.3'
daisy_gateway: '10.20.7.1'
ceph_disk_name: ''
